services:
  db_guardian:
    container_name: db_guardian
    image: docker.io/library/mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${GUARDIAN_DB_PASSWORD}
    ports:
      - "${GUARDIAN_DB_PORT}:3306"
    volumes:
      - "db_guardian_data:/var/lib/mysql"

  db_backend:
    container_name: db_backend
    image: docker.io/library/mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${BACKEND_DB_PASSWORD}
    ports:
      - "${BACKEND_DB_PORT}:3306"
    volumes:
      - "db_backend_data:/var/lib/mysql"

  db_collector:
    container_name: db_collector
    image: mongodb/mongodb-community-server
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_PASSWORD: ${COLLECTOR_DB_PASSWORD}
    ports:
      - "${COLLECTOR_DB_PORT}:27017"
    volumes:
      - "db_collector_data:/data/db"

volumes:
  db_guardian_data:
  db_backend_data:
  db_collector_data:
